version: '3.7'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    depends_on:
      - redis
    restart: unless-stopped
    env_file: .env
    environment:
      - BACKEND_PORT=$BACKEND_PORT
      - OWNER=$OWNER
      - REPO=$REPO
      - REDIS_HOST=redis
      - REDIS_PORT=$REDIS_PORT
    ports:
      - '5000:5000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh redis:6379 -- nodemon index.js
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    depends_on: 
      - backend
    env_file: ./client/.env
    environment:
      - REACT_APP_BACKEND_HOST=backend
      - REACT_APP_BACKEND_PORT=5000
    ports:
      - '8080:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  node_modules: